// language switch actions
export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";
// UI actions
export const UI_MARQUEE = "UI_MARQUEE";
export const UI_TOGGLE_AUTO_CLEAR = "UI_TOGGLE_AUTO_CLEAR";
export const UI_TOGGLE_AUTO_OCR = "UI_TOGGLE_AUTO_OCR";
export const UI_TOGGLE_AUTO_TRANSLATE = "UI_TOGGLE_AUTO_TRANSLATE";
export const UI_SELECT_IMAGE = "UI_SELECT_IMAGE";
export const UI_SET_WHOLE_FONT_FAMILY = "UI_SET_WHOLE_FONT_FAMILY";
export const UI_SET_WHOLE_FONT_SIZE = "UI_SET_WHOLE_FONT_SIZE";
export const UI_SET_WHOLE_FONT_COLOR = "UI_SET_WHOLE_FONT_COLOR";
export const UI_SET_WHOLE_FONT_TEXT_ALIGN = "UI_SET_WHOLE_FONT_TEXT_ALIGN";
export const UI_SET_WHOLE_FONT_LINEHEIGHT = "UI_SET_WHOLE_FONT_LINEHEIGHT";
export const UI_SET_GLOBAL_FONT_STYLE = "UI_SET_GLOBAL_FONT_STYLE";
export const UI_SET_GLOBAL_FONT_WEIGHT = "UI_SET_GLOBAL_FONT_WEIGHT";
export const UI_SET_GLOBAL_FONT_DIRECTION = "UI_SET_GLOBAL_FONT_DIRECTION";
export const UI_SET_GLOBAL_FONT_TEXT_CASE = "UI_SET_GLOBAL_FONT_TEXT_CASE";
export const UI_RECEIVED_CURRENT_SELECTED_ITEM = "UI_RECEIVED_CURRENT_SELECTED_ITEM";
export const UI_RECEIVED_CURRENT_TRANSLATION_ORDERID = "UI_RECEIVED_CURRENT_TRANSLATION_ORDERID";
export const UI_SET_CORRECT_TRANSL_RESULT = "UI_SET_CORRECT_TRANSL_RESULT";
export const UI_ZOOM_CANVAS_BECH = "UI_ZOOM_CANVAS_BECH";
export const UI_OPEN_MODAL = "UI_OPEN_MODAL";
export const UI_CLOSE_MODAL = "UI_CLOSE_MODAL";
export const UI_START_PREVIEW = "UI_START_PREVIEW";
export const UI_CLOSE_PREVIEW = "UI_CLOSE_PREVIEW";
export const UI_SET_START_NUMBER = "UI_SET_START_NUMBER";
export const UI_HANDLER_SET_FONT = "UI_HANDLER_SET_FONT";
export const UI_LOADING_START = "UI_LOADING_START";
export const UI_LOADING_COMPLETE = "UI_LOADING_COMPLETE";
export const UI_SET_CLEAR_PRETRANSL_RESULT = "UI_SET_CLEAR_PRETRANSL_RESULT";
export const UI_SET_STOP_CLEAR_PRETRANSL_RESULT = "UI_SET_STOP_CLEAR_PRETRANSL_RESULT";
export const UI_SET_IS_BACKTO_TRANSLATE_PAGE = "UI_SET_IS_BACKTO_TRANSLATE_PAGE";
export const UI_SET_IS_NOT_BACKTO_TRANSLATE_PAGE = "UI_SET_IS_NOT_BACKTO_TRANSLATE_PAGE";
export const UI_RECEIVED_ERROR_MESSAGE = "UI_RECEIVED_ERROR_MESSAGE";
export const UI_RECEIVED_ORDER_NUMBER = "UI_RECEIVED_ORDER_NUMBER";
export const UI_SET_IS_TO_LAST_CHAPTER = "UI_SET_IS_TO_LAST_CHAPTER";
export const UI_SET_IS_TO_NEXT_CHAPTER = "UI_SET_IS_TO_NEXT_CHAPTER";
export const UI_SET_TOGGLE_REMARK_MODAL = "UI_SET_TOGGLE_REMARK_MODAL";
export const UI_SET_TOGGLE_GLOSSARY_MODAL = "UI_SET_TOGGLE_GLOSSARY_MODAL";

// images actions
export const RECEIVED_IMAGES = "RECEIVED_IMAGES";
export const RECEIVED_SELECTED_IMG = "RECEIVED_SELECTED_IMG";
export const RECEIVED_CROPED_IMG = "RECEIVED_CROPED_IMG";
export const IMAGES_CREATE_TRANSLAREA_BOX = "IMAGES_CREATE_TRANSLAREA_BOX";
export const IMAGES_RECEIVED_MASK_IMG = "IMAGES_RECEIVED_MASK_IMG";
export const IMAGES_RECEIVED_RESULT_BOX_STYLE = "IMAGES_RECEIVED_RESULT_BOX_STYLE";
export const IMAGES_RECEIVED_IMG_STATUS = "IMAGES_RECEIVED_IMG_STATUS";
export const IMAGES_RECEIVED_IMAGES_COLLECTIONS = "IMAGES_RECEIVED_IMAGES_COLLECTIONS";
export const IMAGES_RECEIVED_IMG_HEIGHT = "IMAGES_RECEIVED_IMG_HEIGHT";
export const IMAGES_RECEIVED_TRANSLATION_ORDERID = "IMAGES_RECEIVED_TRANSLATION_ORDERID";
export const IMAGES_DISPLAY_TRANSLPOPUP = "IMAGES_DISPLAY_TRANSLPOPUP";
export const IMAGES_CLEAR_CREATED_TRANSL_BOX = "IMAGES_CLEAR_CREATED_TRANSL_BOX";
export const IMAGES_CLEAR_MASK_TEXT_IMGS = "IMAGES_CLEAR_MASK_TEXT_IMGS";
export const IMAGES_DISPLAY_TRANSLBOX = "IMAGES_DISPLAY_TRANSLBOX";
export const IMAGES_HIDDEN_TRANSLBOX = "IMAGES_HIDDEN_TRANSLBOX";
export const IMAGES_CLEAR_PRE_CROP_AREA = "IMAGES_CLEAR_PRE_CROP_AREA";
export const IMAGES_CLEAR_CROP_BOX = "IMAGES_CLEAR_CROP_BOX";
export const IMAGES_DISPLAY_TRANSL_AREA_BOX = "IMAGES_DISPLAY_TRANSL_AREA_BOX";
export const IMAGES_CLEAR_PRE_MASK_LAYER = "IMAGES_CLEAR_PRE_MASK_LAYER";
export const IMAGES_NOT_CLEAR_PRE_MASK_LAYER = "IMAGES_NOT_CLEAR_PRE_MASK_LAYER";
export const IMAGES_CLEAR_TRANSL_POP_UP = "IMAGES_CLEAR_TRANSL_POP_UP";
export const IMAGES_CREATE_RESULT_LAYER = "IMAGES_CREATE_RESULT_LAYER";
export const IMAGES_CREATE_RESULT_BOX = "IMAGES_CREATE_RESULT_BOX";
export const IMAGES_RECEIVED_FEEDBACK_MESSAGE = "IMAGES_RECEIVED_FEEDBACK_MESSAGE";
export const IMAGES_CLEAR_SELECTED_IMAGE = "IMAGES_CLEAR_SELECTED_IMAGE";
export const IMAGES_DISABLED_SWITCH_CHAPTER = "IMAGES_DISABLED_SWITCH_CHAPTER";
export const IMAGES_DISABLED_LAST_CHAPTER = "IMAGES_DISABLED_LAST_CHAPTER";
export const IMAGES_DISABLED_NEXT_CHAPTER = "IMAGES_DISABLED_NEXT_CHAPTER";
export const IMAGES_ENABLE_SWITCH_CHAPTER = "IMAGES_ENABLE_SWITCH_CHAPTER";
export const IMGAGES_RECEIVED_SELECTED_TRANSLIMAGE = "IMGAGES_RECEIVED_SELECTED_TRANSLIMAGE";
export const IMGAGES_RECEIVED_RESULT_IMGURL = "IMGAGES_RECEIVED_RESULT_IMGURL";

// font settings
export const FONTSETTINGS_SELECT_FONT_FAMILY = "FONTSETTINGS_SELECT_FONT_FAMILY";
export const FONTSETTINGS_SELECT_FONT_SIZE = "FONTSETTINGS_SELECT_FONT_SIZE";
export const FONTSETTINGS_SELECT_FONT_COLOR = "FONTSETTINGS_SELECT_FONT_COLOR";
export const FONTSETTINGS_SELECT_FONT_STYLE = "FONTSETTINGS_SELECT_FONT_STYLE";
export const FONTSETTINGS_SELECT_FONT_WEIGHT = "FONTSETTINGS_SELECT_FONT_WEIGHT";
export const FONTSETTINGS_SELECT_FONT_TEXTALIGN = "FONTSETTINGS_SELECT_FONT_TEXTALIGN";
export const FONTSETTINGS_SELECT_FONT_OUTLINE_COLOR = "FONTSETTINGS_SELECT_FONT_OUTLINE_COLOR";
export const FONTSETTINGS_SELECT_FONT_SHADOW_COLOR = "FONTSETTINGS_SELECT_FONT_SHADOW_COLOR";
export const FONTSETTINGS_SELECT_FONT_OUTLINE_SIZE = "FONTSETTINGS_SELECT_FONT_OUTLINE_SIZE";
export const FONTSETTINGS_SELECT_FONT_SHADOW_SIZE = "FONTSETTINGS_SELECT_FONT_SHADOW_SIZE";
export const FONTSETTINGS_SELECT_LINE_HEIGHT = "FONTSETTINGS_SELECT_LINE_HEIGHT";
export const FONTSETTINGS_SELECT_FONT_DIRECTION = "FONTSETTINGS_SELECT_FONT_DIRECTION";
export const FONTSETTINGS_SELECT_FONT_TEXT_CASE = "FONTSETTINGS_SELECT_FONT_TEXT_CASE";
export const FONTSETTINGS_OPEN_POPUP_ABSORB_COLOR = "FONTSETTINGS_OPEN_POPUP_ABSORB_COLOR";
export const FONTSETTINGS_CLOSE_POPUP_ABSORB_COLOR = "FONTSETTINGS_CLOSE_POPUP_ABSORB_COLOR";
export const FONTSETTINGS_CLEAR_PRE_FONT_SETTINGS = "FONTSETTINGS_CLEAR_PRE_FONT_SETTINGS";

//brush settings
export const BRUSHSETTINGS_BRUSH_WIDTH = "BRUSHSETTINGS_BRUSH_WIDTH";

// glossary settings
export const GLOSSARY_RECEIVED_GLOSSARY_DATA = "GLOSSARY_RECEIVED_GLOSSARY_DATA";
export const GLOSSARY_RECEIVED_ORIGIN_TEXT = "GLOSSARY_RECEIVED_ORIGIN_TEXT";
export const GLOSSARY_RECEIVED_TRANSL_TEXT = "GLOSSARY_RECEIVED_TRANSL_TEXT";