// language switch actions
export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";
// UI actions
export const UI_MARQUEE = "UI_MARQUEE";
export const UI_TOGGLE_AUTO_CLEAR = "UI_TOGGLE_AUTO_CLEAR";
export const UI_TOGGLE_AUTO_OCR = "UI_TOGGLE_AUTO_OCR";
export const UI_TOGGLE_AUTO_TRANSLATE = "UI_TOGGLE_AUTO_TRANSLATE";
export const UI_SELECT_IMAGE = "UI_SELECT_IMAGE";
export const UI_ZOOM_CANVAS_BECH = "UI_ZOOM_CANVAS_BECH";

// images actions
export const RECEIVED_IMAGES = "RECEIVED_IMAGES";
export const RECEIVED_SELECTED_IMG = "RECEIVED_SELECTED_IMG";

