import React from 'react';
import RightMenu from './RightMenu';
import WorkbenchMain from './WorkbenchMain';
import './index.css';

function Workbench(props) {
    const {
        contentText,
        zoomCanvasValue,
        selectedImage,
        selectedTranslImage,
        cropedImage,
        fontSettings,
        openModal,
        closeModal,
        setCropImg,
        createNewCropArea,
        createMaskLayer,
        tabToTranslate,
        brushEvents,
        tabToClearText,
        createdTranslBox,
        hasCropBox,
        modalOpen,
        modalId,
        marquee,
        font,
        brush,
        maskTextImgs,
        correctTransl,
        hasCorrect,
        originORCText,
        translatedText,
        hanlerChangeORCText,
        handlerChangeTranslatedText,
        handerTranslText,
        handlerCompleteTranslate,
        resultLayers,
        displayTranslPopUp,
        displayTranslBox,
        displayResultBox,
        createStartNumber,
        startNumber,
        setResultBoxStyle,
        resultBoxStyleParams,
        selectedImg,
        clearPreTranslResult,
        currentTip,
        status,
        imgHeight,
        receivedImgSize,
        handlerSelectFeedBackMsg,
        handlerSelectReProcess,
        clearPreMask,
        targetLang,
        wholeFontSize,
        wholeFontColor,
        wholeFontTextAlign,
        wholeFontLineHeight,
        globalHasFontItalic,
        globalHasFontWeight,
        globalFontDirection,
        globalFontTextCase,
        handlerCancelCrop,
        handlerConfirmCrop,
        createCropedBox,
        hasCropedMarquee,
        cropedBoxParams,
        clearCropBox,
        fonts,
        wholeFonFamily,
        defaultFontFamily,
        maskColorSettings,
        updatedMaskBackground,
        updateBackground
    } = props;
    const workbenchMainProps = {
        contentText,
        selectedImage,
        selectedTranslImage,
        cropedImage,
        fontSettings,
        openModal,
        closeModal,
        setCropImg,
        createNewCropArea,
        createMaskLayer,
        tabToTranslate,
        brushEvents,
        tabToClearText,
        modalOpen,
        modalId,
        marquee,
        createdTranslBox,
        hasCropBox,
        font,
        brush,
        maskTextImgs,
        correctTransl,
        hasCorrect,
        originORCText,
        translatedText,
        resultLayers,
        hanlerChangeORCText,
        handlerChangeTranslatedText,
        handerTranslText,
        handlerCompleteTranslate,
        scale: zoomCanvasValue,
        displayTranslPopUp,
        displayTranslBox,
        displayResultBox,
        createStartNumber,
        startNumber,
        setResultBoxStyle,
        resultBoxStyleParams,
        selectedImg,
        clearPreTranslResult,
        currentTip,
        status,
        imgHeight,
        receivedImgSize,
        handlerSelectFeedBackMsg,
        clearPreMask,
        wholeFontSize,
        wholeFontColor,
        wholeFontTextAlign,
        wholeFontLineHeight,
        globalHasFontItalic,
        globalHasFontWeight,
        globalFontDirection,
        globalFontTextCase,
        handlerCancelCrop,
        handlerConfirmCrop,
        createCropedBox,
        hasCropedMarquee,
        cropedBoxParams,
        clearCropBox,
        fonts,
        wholeFonFamily,
        defaultFontFamily,
        maskColorSettings,
        updatedMaskBackground,
        updateBackground
    };

    const rightMenuProps = {
        contentText,
        resultLayers,
        handlerSelectReProcess,
        targetLang
    };
    return (
        <div className="workbench">
            <div className="workbench-container">
                <WorkbenchMain {...workbenchMainProps}/>
                <RightMenu {...rightMenuProps}/>
            </div>
        </div>
    )
}

export default Workbench;